version: '3.1'

services:

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pguser
    volumes:
      - db-restore:/var/lib/postgresql/data
      - db-bak:/var/pgbak

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  db-restore:
  db-bak:
